%% process video: step 1, get range
an_neurons = AnalysisPrctile([5 50 95]); % use 95 - 50 / 50 - 5 ratio
an_background = AnalysisPrctile(3); % smoothed, percentile background
an_range = AnalysisRange(); % range for potential circles to extract

reader = connect(...
    ReaderVideo('~/Desktop/mouse3/Data83.video'), ...
    FilterRegisterSift([], true), ...
    FilterDownsample(2), ...
    FilterSmoothTime(3), ...
    an_neurons, ...
    an_range, ...
    FilterGauss(3, 7), ...
    an_background ...
);

% run
reader.run();


%% background subtraction
[reader, writer] = connect(...
    ReaderVideo('~/Desktop/mouse3/Data81.video'), ...
    FilterRegisterSift([], true), ...
    FilterDownsample(2), ...
    FilterSmoothTime(3), ...
    FilterSubtract(background), ...
    WriterVariable() ...
);

reader.run();
video = writer.getResult();

clear reader writer;
