%% process video: step 1, get range
% skip background, less temporal smoothing
an_neurons = AnalysisPrctile([5 50 95]); % use 95 - 50 / 50 - 5 ratio
an_background = AnalysisPrctile(3); % smoothed, percentile background
an_range = AnalysisRange(); % range for potential circles to extract

reader = connect(...
    ReaderVideo('~/Desktop/mouse3/Data85.video'), ...
    FilterRegisterSift([], true), ...
    FilterDownsample(2), ...
    FilterSmoothTime(2), ...
    an_neurons, ...
    an_range ...
);

% run
reader.run();
